language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
  - pip install flake8
install:
  - sudo python setup.py install
script:
  - flake8 . --exclude __init__.py
  - py.test tests/
