site_name: l293d
site_url: https://jamesevickery.github.io/l293d/
site_description: Python module to drive DC motors from a Raspberry Pi using the L293D chip
site_author: James Vickery

repo_url: https://github.com/jamesevickery/l293d

pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
    - Hardware Setup: user-guide/hardware-setup.md
    - Python Scripts: user-guide/python-scripts.md
    - Configuration: user-guide/configuration.md
- Methods:
    - Clockwise and Anticlockwise: methods/clockwise-anticlockwise.md
- About:
    - Support: about/support.md
    - Contributing: about/contributing.md
    - Sources: about/sources.md
    - License: about/license.md
